networks:
  internal:
    driver: bridge

services:
  db:
    image: postgres:latest
    container_name: postgres
    env_file: .env
    restart: always
    ports:
      - "5432:5432"
    networks:
      - internal